- hosts: localhost
  roles:
  - role: ome.omero_server
  vars:
    ice_version: "3.6"
    ice_install_devel: False
    ice_install_python: False
    omero_server_database_manage: False
    omero_server_systemd_setup: False
    omero_server_system_uid: 1000
    omero_server_virtualenv: True
    omero_server_python3: True
